MapTopic:                   '/map_generator/global_cloud' #'/voxel_map'

TargetTopic:                '/goal' #'/move_base_simple/goal'

DilateRadius2d:              0.2 # 0.113 #0.5   0.2m半径宽 r=4

DilateRadius_zupper:         0.113

DilateRadius_zlower:         0.113

VoxelWidth:                 0.05 #0.25

MapBound:                  [-25.0, 25.0, -25.0, 25.0, 0.0, 5.0] #[-1.5, 10.0, -16.0, 1.1, -0.1, 0.511] #[-25.0, 25.0, -25.0, 25.0, 0.0, 5.0]

TimeoutRRT:                 0.02

MaxVelMag:                  4.0

MaxBdrMag:                  2.1

MaxTiltAngle:               1.05

MinThrust:                  2.0

MaxThrust:                  12.0

VehicleMass:                0.61

GravAcc:                    9.8

HorizDrag:                  0.70

VertDrag:                   0.80

ParasDrag:                  0.01

SpeedEps:                   0.0001

WeightT:                    20.0

ChiVec:                     [1.0e+4, 1.0e+4, 1.0e+4, 1.0e+4]

SmoothingEps:               1.0e-2

IntegralIntervs:            16

RelCostTol:                 1.0e-5
